## About Dataset


**Rows**: Each row represents a unique Spotify user.

**Columns**:

        user_id → Unique identifier for each user
        
        gender → User gender (Male/Female/Other)
        
        age → User age
        
        country → User location
        
        subscription_type → Type of Spotify subscription (Free, Premium, Family, Student)
        
        listening_time → Minutes spent listening per day
        
        songs_played_per_day → Number of songs played daily
        
        skip_rate → Percentage of songs skipped
        
        device_type → Device used (Mobile, Desktop, Web)
        
        ads_listened_per_week → Number of ads heard per week
        
        offline_listening → Offline mode usage

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [2]:
df = pd.read_csv("spotify_churn_dataset.csv")
print("Cinq premieres lignes : ")
df.head()

Cinq premieres lignes :

,user_id,gender,age,country,subscription_type,listening_time,songs_played_per_day,skip_rate,device_type,ads_listened_per_week,offline_listening,is_churned
0,1,Female,54,CA,Free,26,23,0.20,Desktop,31,0,1
1,2,Other,33,DE,Family,141,62,0.34,Web,0,1,0
2,3,Male,38,AU,Premium,199,38,0.04,Mobile,0,1,1
3,4,Female,22,CA,Student,36,2,0.31,Mobile,0,1,0
4,5,Other,29,US,Family,250,57,0.36,Mobile,0,1,1

In [3]:
print(f"Taille : {df.shape[0]} lignes | {df.shape[1]} colonnes")

Taille : 8000 lignes | 12 colonnes

In [4]:
df.drop(columns = ['is_churned', 'user_id'], axis=1 , inplace=True)

In [5]:
print(f"Taille : {df.shape[0]} lignes | {df.shape[1]} colonnes")

Taille : 8000 lignes | 10 colonnes

In [6]:
df.head()

,gender,age,country,subscription_type,listening_time,songs_played_per_day,skip_rate,device_type,ads_listened_per_week,offline_listening
0,Female,54,CA,Free,26,23,0.20,Desktop,31,0
1,Other,33,DE,Family,141,62,0.34,Web,0,1
2,Male,38,AU,Premium,199,38,0.04,Mobile,0,1
3,Female,22,CA,Student,36,2,0.31,Mobile,0,1
4,Other,29,US,Family,250,57,0.36,Mobile,0,1

In [15]:
print("Elements vides par colonnes : ")
print("-----------------------------")
df.isna().sum()

Elements vides par colonnes :
-----------------------------

gender                   0
age                      0
country                  0
subscription_type        0
listening_time           0
songs_played_per_day     0
skip_rate                0
device_type              0
ads_listened_per_week    0
offline_listening        0
dtype: int64

**Pas de valeurs manquantes dans ce dataset**

### PROPORTIONS PAR VARIABLES CATEGORIELLLES

In [21]:
print("Proportion de repartition sur le genre : ")
df['gender'].value_counts(normalize=True)

Proportion de repartition sur le genre :

gender
Male      0.336375
Female    0.332375
Other     0.331250
Name: proportion, dtype: float64

**La répartition du dataset est parfait le genre.**

In [22]:
print("Proportion de repartition sur le type de subscription : ")
df['subscription_type'].value_counts(normalize=True)

Proportion de repartition sur le type de subscription :

subscription_type
Premium    0.264375
Free       0.252250
Student    0.244875
Family     0.238500
Name: proportion, dtype: float64

**La répartition du dataset est parfait le type de souscription.**

In [23]:
print("Proportion de repartition sur le type d'appareil : ")
df['device_type'].value_counts(normalize=True)

Proportion de repartition sur le type d'appareil :

device_type
Desktop    0.347250
Web        0.327875
Mobile     0.324875
Name: proportion, dtype: float64

**La répartition du dataset est parfait le type de souscription.**

In [24]:
print("Proportion de repartition sur les pays : ")
df['country'].value_counts(normalize=True)

Proportion de repartition sur les pays :

country
AU    0.129250
US    0.129000
DE    0.126875
IN    0.126375
PK    0.124875
FR    0.123625
UK    0.120750
CA    0.119250
Name: proportion, dtype: float64

**La répartition du dataset est parfait les pays.**